version: 2
jobs:
  build:
    docker:
      - image: circleci/node 
    working_directory: ~/rchain.cloud
    environment:
      DOCKER_USER: ijsfd
      DOCKER_PASS: mandrilo
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Install dependencies
          command: npm install
      # Build and publish to Docker Hub
      - run: |
          echo $DOCKER_USER
          echo $DOCKER_PASS
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t rchaincommunity/rchaincloudbackend:latest -f Dockerfile.backend
          docker push rchaincommunity/rchaincloudbackend:latest