version: 2
jobs:
  build:
    context: rchaincloud
    docker:
      - image: circleci/node 
    working_directory: ~/rchain.cloud
    steps:
      - checkout
      - setup_remote_docker

      # Build and publish to Docker Hub
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -f Dockerfile.backend . -t rchaincommunity/rchaincloudbackend:latest
          docker build -f Dockerfile.frontend . -t rchaincommunity/rchaincloudfrontend:latest
          docker push rchaincommunity/rchaincloudbackend:latest
          docker push rchaincommunity/rchaincloudfrontend:latest          