version: 2
jobs:
  branches:
    only:
      - /circleci/
  backend:
    docker:
      - image: node:8.12.0-alpine       
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  frontend:
    docker:
      - image: node:8.12.0-alpine
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm start
workflows:
  version: 2
  build_and_run:
    jobs:
      - backend
      - frontend
