version: 2
jobs:
  backend:
    docker:
      - image: node:8.12.0-alpine
      
    working_directory: ~/rchain.cloud

    steps:
      - checkout
      - npm install
      - npm start
  frontend:
    docker:
      - image: node:8.12.0-alpine

    working_directory: ~/rchain.cloud

    steps:
      - checkout
      - yarn install
      - yarn start
workflows:
  version: 2
  build:
    jobs:
      - backend
	  filters:
	    branches:
	      only:
		- circleci
		- react 
      - frontend
          filters:
            branches:
              only:
                - circleci
                - react

      



